version: "2.3"

# Use this file for an example for production

services:
  mariadb:
    image: mariadb:10.2.14
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=iop
      - MYSQL_DATABASE=phpmyfaq
      - MYSQL_USER=phpmyfaq
      - MYSQL_PASSWORD=phpmyfaq
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
  phpmyfaq:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    environment:
      - PMF_DB_HOST=db
      - PMF_DB_NAME=phpmyfaq
      - PMF_DB_USER=phpmyfaq
      - PMF_DB_PASS=phpmyfaq
      - PMF_DISABLE_HTACCESS=""
      - PMF_TIMEZONE="Europe/Berlin"
      - PMF_ENABLE_UPLOADS="On"
      - PMF_MEMORY_LIMIT="64M"
      - PHP_LOG_ERRORS="On"
      - PHP_ERROR_REPORTING="E_ALL" # Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
      - PHP_POST_MAX_SIZE="64M"
      - PHP_UPLOAD_MAX_FILESIZE="64M"
    links:
      - mariadb:db
      - elasticsearch
    ports:
      - "8080:80"
    volumes:
      - ./volumes/phpmyfaq/attachments:/var/www/html/attachments
      - ./volumes/phpmyfaq/data:/var/www/html/data
      - ./volumes/phpmyfaq/images:/var/www/html/images
      - ./volumes/phpmyfaq/config:/var/www/html/config
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    stdin_open: true
    links:
      - mariadb:db
    ports:
      - "8000:80"
    volumes:
      - ./volumes/sessions:/sessions
  elasticsearch:
    image: elasticsearch:2.4.6
    restart: always
    environment:
      - cluster.name=phpmyfaq-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
